### ISSUE TITLE
White border on square covers

### ISSUE THREAD

**Issue by chocolatechipcats** [darklinkpower/Mythic#11]
### Bug Description

In details view, more square-ish covers have an ugly white border.

### To Reproduce

Cover for replication:

![0651b56d-20ee-4fee-a6ac-5e778a3f4212](https://user-images.githubusercontent.com/47759676/209608576-d0aecbb0-88cc-4f67-b32f-0442be01a061.jpg)

### Screenshots

![](https://cdn.discordapp.com/attachments/808419347105447957/1056857420233707560/image.png)

**Comment by chocolatechipcats** [comment]
Seems to work as expected in grid mode 
![2022-12-26 23_59_25-Window](https://user-images.githubusercontent.com/47759676/209608922-1f1f69e1-ffdc-4151-a9e6-6c8a59f7b4ed.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/Mythic/commit/aaab3e7d9a7631519a8363d2464e706cb798e4c8



> Seems to work as expected in grid mode, assuming that dark-grey is intended
> 
> ![2022-12-26 23_59_25-Window](https://user-images.githubusercontent.com/47759676/209608922-1f1f69e1-ffdc-4151-a9e6-6c8a59f7b4ed.png)

This can be disabled by the "Draw grid item background" setting
