### ISSUE TITLE
Missing ThemeModifier Value

### ISSUE THREAD

**Issue by PruglePin** [darklinkpower/Mythic#2]
The border color in Grid View mode cannot be changed through ThemeModifier.
![download](https://user-images.githubusercontent.com/101024544/156902718-0fd1b9fe-6a71-4c86-82de-d4e4094dc2c0.png)

**Comment by darklinkpower** [comment]
I've made the border use `GlyphBrush` in https://github.com/darklinkpower/Mythic/commit/e62c1e24cec26e801505757197d04c275856440a
