### ISSUE TITLE
The background color of the header image is too dark!!!

### ISSUE THREAD

**Issue by asd990323** [darklinkpower/Mythic#24]
### Feature Description

The background color of the header image is too dark. Can we make the background image brighter?

### Screenshots

![Snipaste_2024-08-09_17-00-25](https://github.com/user-attachments/assets/f2e385ec-6eee-46dd-aa12-9ef49269c1da)

**Comment by darklinkpower** [comment]
Sorry for not replying. An option is provided via the ThemeModifier extension:

![image](https://github.com/user-attachments/assets/9eaea895-b810-4a61-ac68-9358b0a1b0e1)
