### ISSUE TITLE
Make height of screenshotsvisualizer panel in Details view adjustable

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/Mythic#5]
### Feature Description

I like to have the Screenshots tab selected as I browse through games in Details view, but the fixed height of 550 is too tall for my needs. Most of my games have too few pictures to utilize most of the space. I changed the value manually in the xml, but it would be nice if it could be changed via a slider in ThemeModifier so I wouldn't have to make this adjustment after every update.

The fixed heights of the other tabs makes more sense, since there's usually enough content to use all of the given space.

**Comment by darklinkpower** [comment]
Why was this closed?
