### ISSUE TITLE
Can I override applogo.ico?

### ISSUE THREAD

**Issue by chocolatechipcats** [darklinkpower/Mythic#8]
### Feature Description

I prefer the Playnite default orange icon for the system tray, so I've overwritten applogo.ico in the theme folder. However, every time Mythic updates I have to repeat the process. Is there a method that I missed for overriding it without this happening?

Thanks :)

**Comment by darklinkpower** [comment]
Sorry for the late reply, I've been taking a break from Playnite work in general.

I'm afraid that there's no way to prevent it from overriding.
